# interno
kind: Service
apiVersion: v1
metadata:
  name: oauth
spec:
  selector:
    app: oauth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# externo
apiVersion: v1
kind: Service
metadata:
  name: oauth-external
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: oauth
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 62.82.24.134/32
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: oauth:latest
          ports:
            - name: http
              containerPort: 5000